name: Running Gosec Scanning Go Code

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  scanning-go-code:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Go Code Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif -severity high -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505 ./...'
      - name: Upload Vulnerability to Code scanning alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
